<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>ExtrusionUI.Logic.Navigation</AssemblyTitle>
    <Product>ExtrusionUI.Logic.Navigation</Product>
    <Copyright>Copyright ©  2018</Copyright>
    <AssemblyVersion>1.5.3.0</AssemblyVersion>
    <FileVersion>1.5.3.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
    <PackageReference Include="Unity" Version="5.11.10" />
  </ItemGroup>
</Project>