<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PresentationFramework.Aero2" />
    <Reference Include="ZedGraph">
      <HintPath>..\ExtrusionUI.Startup\dll\ZedGraph\ZedGraph.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FontAwesome.WPF">
      <Version>4.7.0.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf">
      <Version>1.1.77</Version>
    </PackageReference>
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="SharpVectors.Reloaded">
      <Version>1.8.4</Version>
    </PackageReference>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Runtime.Caching" Version="8.0.0" />
    <PackageReference Include="Unity" Version="5.11.10" />
    <PackageReference Include="Unity.Container" Version="5.11.11" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\FILABOT_LOGO_2017.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExtrusionUI.Core\ExtrusionUI.Core.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Infrastructure.UI\ExtrusionUI.Infrastructure.UI.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.Filament\ExtrusionUI.Logic.Filament.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.FileOperations\ExtrusionUI.Logic.FileOperations.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.Helpers\ExtrusionUI.Logic.Helpers.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.ModbusTCP\ExtrusionUI.Logic.ModbusTCP.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.Navigation\ExtrusionUI.Logic.Navigation.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.SerialCommunications\ExtrusionUI.Logic.SerialCommunications.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.UI_Intelligence\ExtrusionUI.Logic.UI_Intelligence.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Toolkits\ExtrusionUI.Toolkits.csproj" />
    <ProjectReference Include="..\ExtrusionUI.WindowForms.ZedGraphUserControl\ExtrusionUI.WindowForms.ZedGraphUserControl.csproj" />
  </ItemGroup>
</Project>