<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExtrusionUI.Infrastructure\ExtrusionUI.Infrastructure.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Toolkits\ExtrusionUI.Toolkits.csproj" />
    <ProjectReference Include="..\ExtrusionUI.VirtualKeyboard\ExtrusionUI.VirtualKeyboard.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.6.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="New folder\BooleanSwitchView.xaml.cs" />
    <Compile Remove="New folder\BooleanSwitchViewModel.cs" />
    <Compile Remove="New folder\ButtonPressView.xaml.cs" />
    <Compile Remove="New folder\ButtonPressViewModel.cs" />
    <Compile Remove="New folder\DashboardItemView.xaml.cs" />
    <Compile Remove="New folder\DashboardItemViewModel.cs" />
    <Compile Remove="New folder\DataInputView.xaml.cs" />
    <Compile Remove="New folder\DataInputViewModel.cs" />
    <Compile Remove="New folder\DoubleInputView.xaml.cs" />
    <Compile Remove="New folder\DoubleInputViewModel.cs" />
    <Compile Remove="New folder\EnumItemsView.xaml.cs" />
    <Compile Remove="New folder\EnumItemsViewModel.cs" />
    <Compile Remove="New folder\ErrorItemView.xaml.cs" />
    <Compile Remove="New folder\ErrorItemViewModel.cs" />
    <Compile Remove="New folder\LargeDataInputView.xaml.cs" />
    <Compile Remove="New folder\LargeDataInputViewModel.cs" />
    <Compile Remove="New folder\ViewModelBase.cs" />
    <Page Remove="New folder\BooleanSwitchView.xaml" />
    <Page Remove="New folder\ButtonPressView.xaml" />
    <Page Remove="New folder\DashboardItemView.xaml" />
    <Page Remove="New folder\DataInputView.xaml" />
    <Page Remove="New folder\DoubleInputView.xaml" />
    <Page Remove="New folder\EnumItemsView.xaml" />
    <Page Remove="New folder\ErrorItemView.xaml" />
    <Page Remove="New folder\LargeDataInputView.xaml" />
  </ItemGroup>
</Project>