<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>indicator_icon_8x8_icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.SelfHost">
      <Version>2.2.3</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Prism.Container.Extensions" Version="8.0.62" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Unity" Version="5.11.10" />
    <PackageReference Include="Unity.Abstractions" Version="5.11.7" />
    <PackageReference Include="Unity.Container" Version="5.11.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExtrusionUI.Logic.Filament\ExtrusionUI.Logic.Filament.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.FileOperations\ExtrusionUI.Logic.FileOperations.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.ModbusTCP\ExtrusionUI.Logic.ModbusTCP.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.Navigation\ExtrusionUI.Logic.Navigation.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.SerialCommunications\ExtrusionUI.Logic.SerialCommunications.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.UI_Intelligence\ExtrusionUI.Logic.UI_Intelligence.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Module.Display\ExtrusionUI.Module.Display.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Toolkits\ExtrusionUI.Toolkits.csproj" />
    <ProjectReference Include="..\ExtrusionUI.VirtualKeyboard\ExtrusionUI.VirtualKeyboard.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="indicator_icon_8x8_icon.ico" />
  </ItemGroup>
</Project>