<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExtrusionUI.Core\ExtrusionUI.Core.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Infrastructure.UI\ExtrusionUI.Infrastructure.UI.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Infrastructure\ExtrusionUI.Infrastructure.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.FileOperations\ExtrusionUI.Logic.FileOperations.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.Helpers\ExtrusionUI.Logic.Helpers.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.SerialCommunications\ExtrusionUI.Logic.SerialCommunications.csproj" />
    <ProjectReference Include="..\ExtrusionUI.WindowForms.ZedGraphUserControl\ExtrusionUI.WindowForms.ZedGraphUserControl.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="ZedGraph" Version="5.1.7" />
  </ItemGroup>
</Project>