<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
    <PackageReference Include="Unity" Version="5.11.10" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Behaviours - Copy\MouseBehaviour.cs" />
    <Compile Remove="DependantView.cs" />
    <Compile Remove="PrismExtensions - Copy\DependantView.cs" />
    <Compile Remove="PrismExtensions - Copy\DependantViewAttribute.cs" />
    <Compile Remove="PrismExtensions - Copy\DependantViewRegionBehavior.cs" />
    <Compile Remove="PrismExtensions - Copy\SetPropertyValue.cs" />
    <Compile Remove="Wpf - Copy\EnumToVisibilityConverter.cs" />
    <Compile Remove="Wpf - Copy\FalseToCollapsedConverter.cs" />
    <Compile Remove="Wpf - Copy\FalseToHiddenConverter.cs" />
    <Compile Remove="Wpf - Copy\FontHelper.cs" />
    <Compile Remove="Wpf - Copy\InputBindingsManager.cs" />
    <Compile Remove="Wpf - Copy\MM_Converter.cs" />
    <Compile Remove="Wpf - Copy\TrueToCollapsedConverter.cs" />
    <Compile Remove="Wpf - Copy\TrueToHiddenConverter.cs" />
    <Compile Remove="Wpf - Copy\UriHelper.cs" />
    <Compile Remove="Wpf - Copy\WpfHelper.cs" />
  </ItemGroup>
</Project>