<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>ExtrusionUI.Logic.SerialCommunications</AssemblyTitle>
    <Product>ExtrusionUI.Logic.SerialCommunications</Product>
    <Copyright>Copyright ©  2018</Copyright>
    <AssemblyVersion>1.5.3.0</AssemblyVersion>
    <FileVersion>1.5.3.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExtrusionUI.Logic.FileOperations\ExtrusionUI.Logic.FileOperations.csproj" />
    <ProjectReference Include="..\ExtrusionUI.Logic.Helpers\ExtrusionUI.Logic.Helpers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nefarius.PInvokeSerialPort" Version="1.0.16" />
  </ItemGroup>
</Project>